What would be the output for these codes:
(i) def foo():
    try:
        return 1
    finally:
        return 2

    k = foo()
    print(k)

Output: 2

(ii) def a():
    try:
        f(x, 4)
    finally:
        print('after f')
    print('after f?')

    a()

Output: NameError: name 'f' is not defined
